// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncTrip.Api.Infrastructure.Data;

#nullable disable

namespace SyncTrip.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116154457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Convoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Convoys_Code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Convoys_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Convoys_Status");

                    b.ToTable("Convoys", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.ConvoyParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvoyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConvoyId")
                        .HasDatabaseName("IX_ConvoyParticipants_ConvoyId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ConvoyParticipants_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConvoyParticipants_UserId");

                    b.HasIndex("ConvoyId", "UserId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_ConvoyParticipants_Unique_Active")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("ConvoyParticipants", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.LocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LocationHistories_Timestamp");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_LocationHistories_TripId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LocationHistories_UserId");

                    b.HasIndex("TripId", "UserId", "Timestamp")
                        .HasDatabaseName("IX_LocationHistories_TripId_UserId_Timestamp");

                    b.ToTable("LocationHistories", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_MagicLinkTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MagicLinkTokens_UserId");

                    b.HasIndex("ExpiresAt", "IsUsed")
                        .HasDatabaseName("IX_MagicLinkTokens_ExpiresAt_IsUsed");

                    b.ToTable("MagicLinkTokens", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ConvoyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConvoyId")
                        .HasDatabaseName("IX_Messages_ConvoyId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Messages_IsDeleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Messages_UserId");

                    b.HasIndex("ConvoyId", "SentAt")
                        .HasDatabaseName("IX_Messages_ConvoyId_SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConvoyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PlannedArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PlannedDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutePreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConvoyId")
                        .HasDatabaseName("IX_Trips_ConvoyId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Trips_Status");

                    b.HasIndex("ConvoyId", "Status")
                        .HasDatabaseName("IX_Trips_ConvoyId_Status");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Waypoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsReached")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_Waypoints_TripId");

                    b.HasIndex("TripId", "Order")
                        .HasDatabaseName("IX_Waypoints_TripId_Order");

                    b.ToTable("Waypoints", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.ConvoyParticipant", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.Convoy", "Convoy")
                        .WithMany("Participants")
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncTrip.Api.Core.Entities.User", "User")
                        .WithMany("ConvoyParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convoy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.LocationHistory", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.Trip", "Trip")
                        .WithMany("LocationHistory")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncTrip.Api.Core.Entities.User", "User")
                        .WithMany("LocationHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.MagicLinkToken", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.User", "User")
                        .WithMany("MagicLinkTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Message", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.Convoy", "Convoy")
                        .WithMany("Messages")
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncTrip.Api.Core.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Convoy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Trip", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.Convoy", "Convoy")
                        .WithMany("Trips")
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convoy");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Waypoint", b =>
                {
                    b.HasOne("SyncTrip.Api.Core.Entities.Trip", "Trip")
                        .WithMany("Waypoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Convoy", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.Trip", b =>
                {
                    b.Navigation("LocationHistory");

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("SyncTrip.Api.Core.Entities.User", b =>
                {
                    b.Navigation("ConvoyParticipations");

                    b.Navigation("LocationHistory");

                    b.Navigation("MagicLinkTokens");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
