# Script d'initialisation Solution SyncTrip (Clean Architecture)
# Auteur: Generated by Gemini for User
# Date: 23 Novembre 2025
# Version: 2.0 (Renamed to SyncTrip)

$SolutionName = "SyncTrip"
$BaseDir = Get-Location

Write-Host "--------------------------------------------------" -ForegroundColor Cyan
Write-Host "INITIALISATION DE LA SOLUTION : $SolutionName" -ForegroundColor Yellow
Write-Host "Dossier cible : $BaseDir" -ForegroundColor Cyan
Write-Host "--------------------------------------------------" -ForegroundColor Cyan

# 1. Création de la solution vide
Write-Host "1. Création du fichier solution (.sln)..." -ForegroundColor Green
dotnet new sln -n $SolutionName

# 2. Création des projets (Clean Architecture Layers)

# --- CORE (Domain Layer) ---
# Contient les entités, enums, interfaces. Aucune dépendance externe.
Write-Host "2. Création du projet CORE (Domain)..." -ForegroundColor Green
dotnet new classlib -n "$SolutionName.Core" -o "src/$SolutionName.Core"

# --- APPLICATION (Use Cases) ---
# Contient la logique métier. Dépend de Core.
Write-Host "3. Création du projet APPLICATION (Use Cases)..." -ForegroundColor Green
dotnet new classlib -n "$SolutionName.Application" -o "src/$SolutionName.Application"

# --- INFRASTRUCTURE (External Services) ---
# Implémente les interfaces. Dépend de Application et Core.
Write-Host "4. Création du projet INFRASTRUCTURE (Services)..." -ForegroundColor Green
dotnet new classlib -n "$SolutionName.Infrastructure" -o "src/$SolutionName.Infrastructure"

# --- API (Presentation Layer) ---
# L'API REST et SignalR.
Write-Host "5. Création du projet API (Backend)..." -ForegroundColor Green
dotnet new webapi -n "$SolutionName.API" -o "src/$SolutionName.API"

# --- MOBILE (Client MAUI) ---
# L'application mobile.
Write-Host "6. Création du projet MOBILE (MAUI)..." -ForegroundColor Green
dotnet new maui -n "$SolutionName.Mobile" -o "src/$SolutionName.Mobile"

# --- SHARED (DTOs communs) ---
# Objets partagés entre l'API et le Mobile pour éviter la duplication
Write-Host "7. Création du projet SHARED (DTOs)..." -ForegroundColor Green
dotnet new classlib -n "$SolutionName.Shared" -o "src/$SolutionName.Shared"

# 3. Ajout des projets à la solution
Write-Host "8. Rattachement des projets à la solution..." -ForegroundColor Cyan
dotnet sln add "src/$SolutionName.Core/$SolutionName.Core.csproj"
dotnet sln add "src/$SolutionName.Application/$SolutionName.Application.csproj"
dotnet sln add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj"
dotnet sln add "src/$SolutionName.API/$SolutionName.API.csproj"
dotnet sln add "src/$SolutionName.Mobile/$SolutionName.Mobile.csproj"
dotnet sln add "src/$SolutionName.Shared/$SolutionName.Shared.csproj"

# 4. Gestion des références (Dépendances)
Write-Host "9. Configuration des références entre projets..." -ForegroundColor Cyan

# Core ne dépend de rien (sauf Shared éventuellement pour des Enums communs)
dotnet add "src/$SolutionName.Core/$SolutionName.Core.csproj" reference "src/$SolutionName.Shared/$SolutionName.Shared.csproj"

# Application dépend de Core et Shared
dotnet add "src/$SolutionName.Application/$SolutionName.Application.csproj" reference "src/$SolutionName.Core/$SolutionName.Core.csproj"
dotnet add "src/$SolutionName.Application/$SolutionName.Application.csproj" reference "src/$SolutionName.Shared/$SolutionName.Shared.csproj"

# Infrastructure dépend de Application et Core
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" reference "src/$SolutionName.Application/$SolutionName.Application.csproj"
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" reference "src/$SolutionName.Core/$SolutionName.Core.csproj"

# API dépend de Infrastructure, Application et Shared
dotnet add "src/$SolutionName.API/$SolutionName.API.csproj" reference "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj"
dotnet add "src/$SolutionName.API/$SolutionName.API.csproj" reference "src/$SolutionName.Application/$SolutionName.Application.csproj"
dotnet add "src/$SolutionName.API/$SolutionName.API.csproj" reference "src/$SolutionName.Shared/$SolutionName.Shared.csproj"

# Mobile dépend de Shared (pour les DTOs)
dotnet add "src/$SolutionName.Mobile/$SolutionName.Mobile.csproj" reference "src/$SolutionName.Shared/$SolutionName.Shared.csproj"

# 5. Ajout des packages NuGet essentiels (Open Source)
Write-Host "10. Installation des packages NuGet (Stack Open Source)..." -ForegroundColor Magenta

# API & Infra : EF Core Postgres, SignalR
# Note: On utilise Npgsql pour PostgreSQL
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" package Npgsql.EntityFrameworkCore.PostgreSQL
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" package MailKit
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" package StackExchange.Redis
dotnet add "src/$SolutionName.Infrastructure/$SolutionName.Infrastructure.csproj" package Microsoft.Extensions.Configuration.Abstractions

# Application : FluentValidation pour la validation des entrées
dotnet add "src/$SolutionName.Application/$SolutionName.Application.csproj" package FluentValidation
dotnet add "src/$SolutionName.Application/$SolutionName.Application.csproj" package FluentValidation.DependencyInjectionExtensions
dotnet add "src/$SolutionName.Application/$SolutionName.Application.csproj" package MediatR

# Mobile : Mapsui, CommunityToolkit
dotnet add "src/$SolutionName.Mobile/$SolutionName.Mobile.csproj" package Mapsui.Maui
dotnet add "src/$SolutionName.Mobile/$SolutionName.Mobile.csproj" package CommunityToolkit.Mvvm
dotnet add "src/$SolutionName.Mobile/$SolutionName.Mobile.csproj" package Microsoft.AspNetCore.SignalR.Client

Write-Host "--------------------------------------------------" -ForegroundColor Cyan
Write-Host "SUCCES ! La solution $SolutionName est prête." -ForegroundColor Yellow
Write-Host "Vous pouvez ouvrir le fichier .sln avec Visual Studio." -ForegroundColor Cyan
Write-Host "--------------------------------------------------" -ForegroundColor Cyan
Read-Host -Prompt "Appuyez sur Entree pour quitter"