// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncTrip.Infrastructure.Persistence;

#nullable disable

namespace SyncTrip.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124182505_AddProfileAndGarage")]
    partial class AddProfileAndGarage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncTrip.Core.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "https://logo.clearbit.com/yamaha-motor.com",
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://logo.clearbit.com/honda.com",
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://logo.clearbit.com/kawasaki.com",
                            Name = "Kawasaki"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "https://logo.clearbit.com/suzuki.com",
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "https://logo.clearbit.com/ducati.com",
                            Name = "Ducati"
                        },
                        new
                        {
                            Id = 6,
                            LogoUrl = "https://logo.clearbit.com/bmw-motorrad.com",
                            Name = "BMW Motorrad"
                        },
                        new
                        {
                            Id = 7,
                            LogoUrl = "https://logo.clearbit.com/harley-davidson.com",
                            Name = "Harley-Davidson"
                        },
                        new
                        {
                            Id = 8,
                            LogoUrl = "https://logo.clearbit.com/ktm.com",
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 9,
                            LogoUrl = "https://logo.clearbit.com/triumph.co.uk",
                            Name = "Triumph"
                        },
                        new
                        {
                            Id = 10,
                            LogoUrl = "https://logo.clearbit.com/aprilia.com",
                            Name = "Aprilia"
                        },
                        new
                        {
                            Id = 11,
                            LogoUrl = "https://logo.clearbit.com/renault.com",
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 12,
                            LogoUrl = "https://logo.clearbit.com/peugeot.com",
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 13,
                            LogoUrl = "https://logo.clearbit.com/citroen.com",
                            Name = "Citroën"
                        },
                        new
                        {
                            Id = 14,
                            LogoUrl = "https://logo.clearbit.com/dsautomobiles.com",
                            Name = "DS Automobiles"
                        },
                        new
                        {
                            Id = 15,
                            LogoUrl = "https://logo.clearbit.com/volkswagen.com",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 16,
                            LogoUrl = "https://logo.clearbit.com/mercedes-benz.com",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 17,
                            LogoUrl = "https://logo.clearbit.com/audi.com",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 18,
                            LogoUrl = "https://logo.clearbit.com/bmw.com",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 19,
                            LogoUrl = "https://logo.clearbit.com/porsche.com",
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 20,
                            LogoUrl = "https://logo.clearbit.com/opel.com",
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 21,
                            LogoUrl = "https://logo.clearbit.com/toyota.com",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 22,
                            LogoUrl = "https://logo.clearbit.com/nissan.com",
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 23,
                            LogoUrl = "https://logo.clearbit.com/mazda.com",
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 24,
                            LogoUrl = "https://logo.clearbit.com/mitsubishicars.com",
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 25,
                            LogoUrl = "https://logo.clearbit.com/subaru.com",
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 26,
                            LogoUrl = "https://logo.clearbit.com/lexus.com",
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 27,
                            LogoUrl = "https://logo.clearbit.com/ford.com",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 28,
                            LogoUrl = "https://logo.clearbit.com/chevrolet.com",
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 29,
                            LogoUrl = "https://logo.clearbit.com/tesla.com",
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 30,
                            LogoUrl = "https://logo.clearbit.com/jeep.com",
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 31,
                            LogoUrl = "https://logo.clearbit.com/fiat.com",
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 32,
                            LogoUrl = "https://logo.clearbit.com/alfaromeo.com",
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 33,
                            LogoUrl = "https://logo.clearbit.com/lancia.com",
                            Name = "Lancia"
                        },
                        new
                        {
                            Id = 34,
                            LogoUrl = "https://logo.clearbit.com/hyundai.com",
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 35,
                            LogoUrl = "https://logo.clearbit.com/kia.com",
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 36,
                            LogoUrl = "https://logo.clearbit.com/landrover.com",
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 37,
                            LogoUrl = "https://logo.clearbit.com/mini.com",
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 38,
                            LogoUrl = "https://logo.clearbit.com/iveco.com",
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = 39,
                            LogoUrl = "https://logo.clearbit.com/man.eu",
                            Name = "Man"
                        },
                        new
                        {
                            Id = 40,
                            LogoUrl = "https://logo.clearbit.com/dacia.com",
                            Name = "Dacia"
                        });
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Token");

                    b.ToTable("MagicLinkTokens", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.UserLicense", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LicenseType");

                    b.HasIndex("UserId");

                    b.ToTable("UserLicenses", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.UserLicense", b =>
                {
                    b.HasOne("SyncTrip.Core.Entities.User", "User")
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("SyncTrip.Core.Entities.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncTrip.Core.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Brand", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.User", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
