// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncTrip.Infrastructure.Persistence;

#nullable disable

namespace SyncTrip.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209123802_AddConvoyFeature")]
    partial class AddConvoyFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncTrip.Core.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "https://example.com/logos/yamaha.png",
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://example.com/logos/honda.png",
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://example.com/logos/kawasaki.png",
                            Name = "Kawasaki"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "https://example.com/logos/suzuki.png",
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "https://example.com/logos/bmw-motorrad.png",
                            Name = "BMW Motorrad"
                        },
                        new
                        {
                            Id = 6,
                            LogoUrl = "https://example.com/logos/ducati.png",
                            Name = "Ducati"
                        },
                        new
                        {
                            Id = 7,
                            LogoUrl = "https://example.com/logos/ktm.png",
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 8,
                            LogoUrl = "https://example.com/logos/harley-davidson.png",
                            Name = "Harley-Davidson"
                        },
                        new
                        {
                            Id = 9,
                            LogoUrl = "https://example.com/logos/triumph.png",
                            Name = "Triumph"
                        },
                        new
                        {
                            Id = 10,
                            LogoUrl = "https://example.com/logos/aprilia.png",
                            Name = "Aprilia"
                        },
                        new
                        {
                            Id = 11,
                            LogoUrl = "https://example.com/logos/renault.png",
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 12,
                            LogoUrl = "https://example.com/logos/peugeot.png",
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 13,
                            LogoUrl = "https://example.com/logos/citroen.png",
                            Name = "Citroën"
                        },
                        new
                        {
                            Id = 14,
                            LogoUrl = "https://example.com/logos/ds.png",
                            Name = "DS Automobiles"
                        },
                        new
                        {
                            Id = 15,
                            LogoUrl = "https://example.com/logos/alpine.png",
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 16,
                            LogoUrl = "https://example.com/logos/bmw.png",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 17,
                            LogoUrl = "https://example.com/logos/mercedes.png",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 18,
                            LogoUrl = "https://example.com/logos/audi.png",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 19,
                            LogoUrl = "https://example.com/logos/volkswagen.png",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 20,
                            LogoUrl = "https://example.com/logos/porsche.png",
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 21,
                            LogoUrl = "https://example.com/logos/ferrari.png",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 22,
                            LogoUrl = "https://example.com/logos/lamborghini.png",
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 23,
                            LogoUrl = "https://example.com/logos/fiat.png",
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 24,
                            LogoUrl = "https://example.com/logos/alfa-romeo.png",
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 25,
                            LogoUrl = "https://example.com/logos/toyota.png",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 26,
                            LogoUrl = "https://example.com/logos/nissan.png",
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 27,
                            LogoUrl = "https://example.com/logos/mazda.png",
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 28,
                            LogoUrl = "https://example.com/logos/subaru.png",
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 29,
                            LogoUrl = "https://example.com/logos/mitsubishi.png",
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 30,
                            LogoUrl = "https://example.com/logos/ford.png",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 31,
                            LogoUrl = "https://example.com/logos/chevrolet.png",
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 32,
                            LogoUrl = "https://example.com/logos/tesla.png",
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 33,
                            LogoUrl = "https://example.com/logos/jeep.png",
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 34,
                            LogoUrl = "https://example.com/logos/hyundai.png",
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 35,
                            LogoUrl = "https://example.com/logos/kia.png",
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 36,
                            LogoUrl = "https://example.com/logos/fiat-professional.png",
                            Name = "Fiat Professional"
                        },
                        new
                        {
                            Id = 37,
                            LogoUrl = "https://example.com/logos/iveco.png",
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = 38,
                            LogoUrl = "https://example.com/logos/man.png",
                            Name = "MAN"
                        },
                        new
                        {
                            Id = 39,
                            LogoUrl = "https://example.com/logos/scania.png",
                            Name = "Scania"
                        },
                        new
                        {
                            Id = 40,
                            LogoUrl = "https://example.com/logos/volvo-trucks.png",
                            Name = "Volvo Trucks"
                        });
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Convoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("LeaderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("LeaderUserId");

                    b.ToTable("Convoys", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.ConvoyMember", b =>
                {
                    b.Property<Guid>("ConvoyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("ConvoyId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ConvoyMembers", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Token");

                    b.ToTable("MagicLinkTokens", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.UserLicense", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LicenseType");

                    b.HasIndex("UserId");

                    b.ToTable("UserLicenses", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.ConvoyMember", b =>
                {
                    b.HasOne("SyncTrip.Core.Entities.Convoy", "Convoy")
                        .WithMany("Members")
                        .HasForeignKey("ConvoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncTrip.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncTrip.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Convoy");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.UserLicense", b =>
                {
                    b.HasOne("SyncTrip.Core.Entities.User", "User")
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("SyncTrip.Core.Entities.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncTrip.Core.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Brand", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.Convoy", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SyncTrip.Core.Entities.User", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
